export const AUTH_ERROR_MAP = {
  0: 'Invalid authorization type',
  1: 'Could not validate credentials',
  2: 'Invalid fingerPrint',
  3: 'Invalid token',
  4: 'Missing refresh token',
  5: 'Refresh token expired',
  6: 'File is not an image',
  7: 'Неправильный логин или пароль',
  8: 'Password must contain digits',
  9: 'Password must contain uppercase characters',
  10: 'Password lenght must be beetween 8 and 50',
  11: 'Project with this title already exists',
  12: 'Do not have access to this project',
  13: 'Project not found',
  14: 'User already exists',
  15: 'User not found',
  16: 'Invalid username',
  17: 'Wrong username format',
  18: 'Not authenticated',
  19: 'All skill tags must be unique',
  20: 'Minimum one skill tag need to be specified',
}
